### ISSUE TITLE
Serious Issue in the program!

### ISSUE THREAD

**Issue by Akarshghale9** [Frint0/email-enum#17]
When I am trying to run check.py I am getting this error:

`
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver': 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "check.py", line 60, in <module>
    emailEnum()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "check.py", line 26, in emailEnum
    import sites
  File "/home/ubuntu/email-enum/sites.py", line 13, in <module>
    driver = webdriver.Firefox(firefox_options=options)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 
`

**Comment by yevgen2020** [comment]
If you have already run `setup.sh`, type `bash` in the terminal and press `Enter`, otherwise the script will not be able to find  geckodriver in your PATH

**Comment by Frint0** [comment]
Please make sure geckodriver is executable.
