### ISSUE TITLE
[Feature] Do not abort on scraping error (Snapchat Assertion Error `assert "Reset Password" in driver.title`)

### ISSUE THREAD

**Issue by RobertKosten** [Frint0/email-enum#8]
Hi,

I'm currently experiencing an assertion error, because the scraping of snapchat fails. It'd be nice if instead of aborting completely the status would simply indicate an error and the following checks would still be executed (With scraping this kind of thing is bound to happen relatively often).

Thanks for a useful tool :+1: 

PS: Here's the current error at 2019-03-17 10:27 on commit `07f18f5417b44574b296b7ec19cd5658b45e1b80`:

```
Traceback (most recent call last):
  File "check.py", line 60, in <module>
    emailEnum()
  File "/home/rkosten/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/rkosten/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/rkosten/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rkosten/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "check.py", line 34, in emailEnum
    snap_response = sites.snapchatCheck(email)
  File "/home/rkosten/workspace/email-enum/sites.py", line 56, in snapchatCheck
    assert "Reset Password" in driver.title
AssertionError
```

Oddly enough `Reset Password` appears in the page title, no idea why the assertion fails...

**Comment by Frint0** [comment]
Hm, okay. I'll add some exceptions.
