### ISSUE TITLE
Docker(Linux) chmod: geckodriver: operation not permitted

### ISSUE THREAD

**Issue by nsa** [Frint0/email-enum#9]
I'm trying to use *email-enum* with Docker on Linux(Manjaro) but it starts giving errors at Docker build.

## Docker Build

I tried to Docker build with this command `docker build -t email_enum .` and it gave an "**Operation not permitted**" error.

![image](https://user-images.githubusercontent.com/4787945/54493546-61ac4780-48e2-11e9-9c3f-175df28e8261.png)

https://hastebin.com/yixoleyaca.shell (full output of the docker build command)

## Docker Run

After it builds I executed this `docker run --rm email_enum test@gmail.com` and it gave an error.

```bash
Traceback (most recent call last):
  File "/home/enum/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/local/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "check.py", line 60, in <module>
    emailEnum()
  File "/home/enum/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/enum/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/enum/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/enum/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "check.py", line 26, in emailEnum
    import sites
  File "/home/enum/sites.py", line 12, in <module>
    driver = webdriver.Firefox(firefox_options=options)
  File "/home/enum/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/enum/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable may have wrong permissions.
```
https://hastebin.com/leqilumimo.sql (full output of the docker run command)

Could be related with #6

**Comment by Frint0** [comment]
Try running the `docker run` command with `--privileged `.

**Comment by nsa** [comment]
I tried this `docker run --rm --privileged email_enum test@gmail.com` but it looks like nothing changed.

```bash
Traceback (most recent call last):
  File "/home/enum/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/local/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "check.py", line 60, in <module>
    emailEnum()
  File "/home/enum/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/enum/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/enum/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/enum/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "check.py", line 26, in emailEnum
    import sites
  File "/home/enum/sites.py", line 12, in <module>
    driver = webdriver.Firefox(firefox_options=options)
  File "/home/enum/.local/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/enum/.local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 88, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable may have wrong permissions. 
```
https://hastebin.com/yuzelezifi.sql (full output)

**Comment by Frint0** [comment]
Okay, I think I fixed it. Download the updated setup.sh and run the build again, this time without `--privileged`

**Comment by nsa** [comment]
This time I can't even build the docker image with this command `docker build -t email_enum .`

![image](https://user-images.githubusercontent.com/4787945/54498458-b9fe3c00-4918-11e9-8c93-68393e076d8b.png)

https://hastebin.com/qanulokira.shell (full output)

**Comment by Frint0** [comment]
The issue is that Docker containers run as root by default, and in `dockerfile` it says to add the Email-Enum source files as root, and then switch to the low privileged user `enum`, and run setup.sh. Then `setup.sh` tries to edit files that are owned by root, causing the `Permission Denied` error. I'll fix this by making all of the source files writable by anyone before switching to the `enum` user. I'll also add an if statement to check if the geckodriver is already writable. Thanks for reporting this issue.

**Comment by Frint0** [comment]
Fixed. Try running it again with the updated files. Let me know how it goes! :)

**Comment by nsa** [comment]
It worked this time :)

![image](https://user-images.githubusercontent.com/4787945/54508117-b63cda80-4955-11e9-921d-0f971d61b036.png)

https://hastebin.com/feyivulujo.md (full output)

And,

> I'll fix this by making all of the source files writable by anyone

Just a thought, Why didn't you use `chown` instead of giving the permission **777** to `/home/enum`?

**Comment by Frint0** [comment]
No idea. Just the first thing that came to mind. Oh, and a little tip, run docker with `-it` to see the buffer live.
